### ISSUE TITLE
Integrate bootstrapper docker image with the existing helm charts

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#75]
The docker image created in #74, which shall be used to bootstrap the DomiNode apps, needs to be integrated with the existing helm charts so that it is deployed to the existing environments and becomes available for using in the context of each Kubernetes cluster.

**Comment by ricardogsilva** [comment]
Docker image has been published to:

https://hub.docker.com/repository/docker/kartoza/dominode_bootstrapper

**Comment by lucernae** [comment]
I need all available options (and it's description) extracted out as documentation/readme or just create a sample docker-compose.yml file with sample parameters and dummy services.

**Comment by ricardogsilva** [comment]
docker-compose sample file is already there:

https://github.com/dominodeorg/dominode/blob/master/dominode-bootstrapper/tests/interactive/docker-compose.yml

as for existing options, you can call the image like

```
docker run --rm -ti kartoza/dominode_bootstrapper:0.1.0 --help
```

and see what is there. However, since we are still working on it, it is likely that more options will be added in the short term (that is why I've not documented it yet)

**Comment by lucernae** [comment]
Yes, I understand that the list of options will change. No worries.
What I want is a verbose way of saying what parameters goes inside the service and how it is used.
Seeing the example you gave me, I would expect something along this:

A docker-compose file containing a scenario to bootstrap db and minio together, named `docker-compose.bootstrap-db-minio.yml` :

```yaml
version: "3.8"

services:

  bootstrapper:
    image: ricardogsilva/dominode-bootstrapper:0.1.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-myuser}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-mypassword}
      DB_HOST: ${DB_HOST:-db}
      MINIO_HOST: ${MINIO_HOST:-minio}
      MINIO_PROTOCOL: ${MINIO_PROTOCOL:-http}
    command: "bootstrap --db-host ${DB_HOST} --minio-host ${MINIO_HOST} --minio-protocol ${MINIO_PROTOCOL} ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}"
```

The benefit of doing it this way:
- You can override the parameters or environment using docker .env for your local testing
- You can do local testing by copying the sample file as `docker-compose.override.yml` to run this scenario
- I have a clear way of recognizing how the options propagate from environment variable to the `bootstrap` command
- You can suggest the variable name that I will declare in the helm chart. For example, if you use `MINIO_HOST` here, then I will make `minioHost` as deployment parameter in the helm chart.
- I can understand if one variable is used more than once, like `POSTGRES_USER` is used in the db and bootstrap so I need to extract it. However I don't need to extract `PGDATA` because it is not used in `bootstrapper`.
- If you have different scenario, create a separate docker-compose sample file (eg. to bootstrap just the db or minio)
- If you add more options in the future (or changed it) just add it in the docker-compose file, if you add it here that means the chart should support it. I can just track the docker-compose file and I don't have to build/pull the image to see the options. That would be super helpful for me, and I hope less burden for you compared with making a full option documentation.

As a side note, we might need to integrate it with CI to run integration test. I think this specific commands needs prebuilt service so we can test it. I'm not sure if unit test will be enough.
